#!/usr/bin/env node
/**
 * Argus Phase C4 — argus init CLI
 *
 * Guides first-time Argus setup against a target app:
 *   1. Collect target URLs
 *   2. Detect framework from source dir (Next.js / React Router / unknown)
 *   3. Auto-discover routes using C3 route-discoverer
 *   4. Prompt for Slack + GitHub config (fully optional)
 *   5. Write .env with collected values
 *   6. Write src/config/targets.js pre-filled with discovered routes
 *
 * Pure helpers (detectFramework, generateTargetsJs, generateEnvFile) are
 * exported so the test harness can unit-test them without side effects.
 * The interactive main() only runs when this file is the process entry point.
 */

import fs   from 'fs';
import path from 'path';
import readline from 'readline';
import { fileURLToPath } from 'url';
import { discoverRoutes } from '../utils/route-discoverer.js';

const __filename = fileURLToPath(import.meta.url);

// ── C4.1  Framework detection ─────────────────────────────────────────────────

/**
 * Detect the frontend framework used in the given project root by reading its
 * package.json.  Returns 'nextjs', 'react-router', or 'unknown'.
 *
 * @param {string} projectRoot  absolute path to the target app root
 * @returns {'nextjs' | 'react-router' | 'unknown'}
 */
export function detectFramework(projectRoot) {
  if (!projectRoot || !fs.existsSync(projectRoot)) return 'unknown';
  const pkgPath = path.join(projectRoot, 'package.json');
  if (!fs.existsSync(pkgPath)) return 'unknown';
  let pkg;
  try { pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8')); } catch { return 'unknown'; }
  const deps = { ...pkg.dependencies, ...pkg.devDependencies };
  if (deps['next'])                                          return 'nextjs';
  if (deps['react-router-dom'] || deps['react-router'])     return 'react-router';
  return 'unknown';
}

// ── C4.2  targets.js generator ────────────────────────────────────────────────

/**
 * Generate a pre-filled src/config/targets.js from discovered routes.
 *
 * @param {Array<{path:string, name:string, critical:boolean, waitFor:string|null}>} routes
 * @param {{ framework?: string, sourceDir?: string|null, envFile?: string|null }} options
 * @returns {string}
 */
export function generateTargetsJs(routes, options = {}) {
  const { framework = 'unknown', sourceDir = null, envFile = null } = options;

  // Escape for single-quoted JS string literals: backslash → \\ , CR → \r , LF → \n , ' → \'
  const esc = s => String(s ?? '').replace(/\\/g, '\\\\').replace(/\r/g, '\\r').replace(/\n/g, '\\n').replace(/'/g, "\\'");
  const routeLines = routes.length
    ? routes.map(r => {
        const wf = r.waitFor ? `'${esc(r.waitFor)}'` : 'null';
        return `  { path: '${esc(r.path)}', name: '${esc(r.name)}', critical: ${!!r.critical}, waitFor: ${wf} },`;
      }).join('\n')
    : `  { path: '/', name: 'Home', critical: true, waitFor: 'main' },`;

  const autoDiscoverComment =
    framework === 'nextjs'
      ? '// Next.js detected — nextjs discovery enabled'
      : framework === 'react-router'
        ? '// React Router detected — reactRouter discovery enabled (experimental)'
        : '// Set sitemap: true to fetch /sitemap.xml from TARGET_DEV_URL';

  const sourceDirVal = sourceDir
    ? `process.env.ARGUS_SOURCE_DIR ?? '${sourceDir}'`
    : `process.env.ARGUS_SOURCE_DIR ?? null`;
  const envFileVal = envFile
    ? `process.env.ARGUS_ENV_FILE ?? '${envFile}'`
    : `process.env.ARGUS_ENV_FILE ?? null`;

  return `/**
 * ARGUS Target Configuration — generated by argus init
 *
 * Edit to add routes, flows, and API contracts.
 * Run \`npm run crawl\` to start auditing.
 */

export const config = {
  pageSettleMs: 2000,
  screenshotQuality: 90,
  screenshotDiffThreshold: parseFloat(process.env.SCREENSHOT_DIFF_THRESHOLD ?? '0.5'),
  outputDir: process.env.REPORT_OUTPUT_DIR ?? './reports',
};

export const routes = [
${routeLines}
];

export const comparisonRoutes = routes.filter(r => r.critical);

export const apiContracts = [];

export const severityOverrides = {};

export const auth = null;

export const flows = [];

export const codebase = {
  sourceDir: ${sourceDirVal},
  envFile:   ${envFileVal},
};

${autoDiscoverComment}
export const autoDiscover = {
  sitemap:     true,
  nextjs:      ${framework === 'nextjs'},
  reactRouter: ${framework === 'react-router'},
};
`;
}

// ── C4.3  .env generator ──────────────────────────────────────────────────────

/**
 * Generate a .env file with user-supplied configuration values substituted in.
 * Any field that is blank/falsy is rendered as a commented-out placeholder.
 *
 * @param {{ devUrl?:string, stagingUrl?:string, slackToken?:string,
 *           slackSecret?:string, slackCritical?:string, slackWarnings?:string,
 *           slackDigest?:string, githubToken?:string, githubRepo?:string,
 *           sourceDir?:string, envFile?:string }} options
 * @returns {string}
 */
export function generateEnvFile(options = {}) {
  const {
    devUrl       = 'http://localhost:3000',
    stagingUrl   = '',
    slackToken   = '',
    slackSecret  = '',
    slackCritical = '',
    slackWarnings = '',
    slackDigest  = '',
    githubToken  = '',
    githubRepo   = '',
    sourceDir    = '',
    envFile      = '',
  } = options;

  const stagingLine = stagingUrl
    ? `TARGET_STAGING_URL=${stagingUrl}`
    : `# TARGET_STAGING_URL=`;

  const slackSection = slackToken
    ? `SLACK_BOT_TOKEN=${slackToken}
SLACK_SIGNING_SECRET=${slackSecret}
SLACK_CHANNEL_ID=${slackCritical}
SLACK_ALERT_CHANNEL_ID=${slackWarnings}
${slackDigest ? `SLACK_CHANNEL_DIGEST=${slackDigest}` : '# SLACK_CHANNEL_DIGEST='}`
    : `# SLACK_BOT_TOKEN=xoxb-...
# SLACK_SIGNING_SECRET=...
# SLACK_CHANNEL_ID=
# SLACK_ALERT_CHANNEL_ID=`;

  const githubSection = githubToken
    ? `GITHUB_TOKEN=${githubToken}
GITHUB_REPOSITORY=${githubRepo}`
    : `# GITHUB_TOKEN=ghp_...
# GITHUB_REPOSITORY=owner/repo`;

  const sourceDirLine = sourceDir ? `ARGUS_SOURCE_DIR=${sourceDir}` : `# ARGUS_SOURCE_DIR=../my-app/src`;
  const envFileLine   = envFile   ? `ARGUS_ENV_FILE=${envFile}`     : `# ARGUS_ENV_FILE=../my-app/.env`;

  return `# Argus configuration — generated by argus init

# Target URLs (required)
TARGET_DEV_URL=${devUrl}
${stagingLine}

# Slack (optional — omit entirely to use local report.html instead)
${slackSection}

# GitHub PR integration (optional)
${githubSection}

# Codebase analysis + route discovery (optional — enables C1 + C3)
${sourceDirLine}
${envFileLine}

# Auth credentials (only needed when auth is configured in targets.js)
# ARGUS_AUTH_EMAIL=qa@example.com
# ARGUS_AUTH_PASSWORD=...

# Output settings
REPORT_OUTPUT_DIR=./reports
SCREENSHOT_DIFF_THRESHOLD=0.5
`;
}

// ── C4.4  Interactive setup wizard ────────────────────────────────────────────

function createPrompter() {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const ask = q => new Promise(res => rl.question(q, res));
  return { ask, close: () => rl.close() };
}

const tick   = msg => process.stdout.write(`  ✓ ${msg}\n`);
const note   = msg => process.stdout.write(`  ${msg}\n`);
const step   = msg => process.stdout.write(`\n▶ ${msg}\n`);

async function main() {
  process.stdout.write('\n');
  process.stdout.write('  ╔' + '═'.repeat(42) + '╗\n');
  process.stdout.write('  ║     Argus init — first-time setup         ║\n');
  process.stdout.write('  ╚' + '═'.repeat(42) + '╝\n\n');

  const { ask, close } = createPrompter();

  try {
    // Step 1 — Target URLs
    step('Step 1/4 — Target URLs');
    const devUrl    = (await ask('  Dev URL [http://localhost:3000]: ')).trim() || 'http://localhost:3000';
    const stagingUrl = (await ask('  Staging URL (blank to skip): ')).trim();

    // Step 2 — Source code
    step('Step 2/4 — Source Code (enables C1 env-var audit + C3 file-system discovery)');
    const rawSourceDir = (await ask('  App source directory (blank to skip): ')).trim();
    const sourceDir    = rawSourceDir ? path.resolve(rawSourceDir) : '';
    const rawEnvFile   = (await ask('  App .env file (blank to skip): ')).trim();
    const envFilePath  = rawEnvFile   ? path.resolve(rawEnvFile)   : '';

    // Step 3 — Route discovery
    step('Step 3/4 — Route Discovery');

    const framework = sourceDir ? detectFramework(sourceDir) : 'unknown';
    if (sourceDir) note(`Detected framework: ${framework}`);

    const autoDiscoverConfig = {
      sitemap:     true,
      nextjs:      framework === 'nextjs',
      reactRouter: framework === 'react-router',
    };

    const seedRoutes = [
      { path: '/',      name: 'Home',  critical: true,  waitFor: 'main' },
      { path: '/login', name: 'Login', critical: true,  waitFor: 'form' },
    ];

    note('Discovering routes (sitemap + framework structure)...');
    let finalRoutes;
    try {
      finalRoutes = await discoverRoutes(devUrl, sourceDir || null, autoDiscoverConfig, seedRoutes);
      const added = finalRoutes.filter(r => r.discovered).length;
      tick(`Found ${finalRoutes.length} route(s) total (${added} auto-discovered)`);
    } catch (err) {
      note(`Route discovery skipped (${err.message}) — using seed routes`);
      finalRoutes = seedRoutes;
    }

    // Step 4 — Slack + GitHub
    step('Step 4/4 — Slack & GitHub (press Enter to skip each)');
    const slackToken = (await ask('  Slack bot token (xoxb-..., blank to skip): ')).trim();
    let slackSecret = '', slackCritical = '', slackWarnings = '', slackDigest = '';
    if (slackToken) {
      slackSecret   = (await ask('  Slack signing secret: ')).trim();
      slackCritical = (await ask('  Slack critical channel ID (C...): ')).trim();
      slackWarnings = (await ask('  Slack warnings channel ID (C...): ')).trim();
      slackDigest   = (await ask('  Slack digest channel ID (C...): ')).trim();
    }
    const githubToken = (await ask('  GitHub token (ghp_..., blank to skip): ')).trim();
    let githubRepo = '';
    if (githubToken) {
      githubRepo = (await ask('  GitHub repository (owner/repo): ')).trim();
    }

    // Write files
    process.stdout.write('\n');

    const envContent     = generateEnvFile({ devUrl, stagingUrl, slackToken, slackSecret,
                                             slackCritical, slackWarnings, slackDigest,
                                             githubToken, githubRepo, sourceDir, envFile: envFilePath });
    const targetsContent = generateTargetsJs(finalRoutes, { framework, sourceDir, envFile: envFilePath });

    if (fs.existsSync('.env')) {
      console.warn('  ⚠  .env already exists — skipping write to preserve existing credentials. Delete it manually to regenerate.');
    } else {
      fs.writeFileSync('.env', envContent, 'utf8');
      tick('Wrote .env');
    }

    const targetsPath = path.join('src', 'config', 'targets.js');
    fs.mkdirSync(path.dirname(targetsPath), { recursive: true });
    fs.writeFileSync(targetsPath, targetsContent, 'utf8');
    tick(`Wrote ${targetsPath}`);

    process.stdout.write('\n');
    process.stdout.write('  ╔' + '═'.repeat(48) + '╗\n');
    process.stdout.write('  ║  Done! Run `npm run crawl` to start auditing.  ║\n');
    process.stdout.write('  ╚' + '═'.repeat(48) + '╝\n\n');

  } finally {
    close();
  }
}

if (process.argv[1] === __filename) {
  main().catch(err => { console.error('argus init failed:', err.message); process.exit(1); });
}
